name: deploy

on:
  push:
    branches:
      - main
jobs:
  publish:
    uses: blck-snwmn/share-workflows/.github/workflows/reusable-cf-publish.yml@main
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}