name: lint

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: blck-snwmn/share-workflows/go/setup@main
        with:
          working-directory: ./client
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --enable=gosec
          working-directory: ./client
  eslint:
    permissions:
      pull-requests: write
      contents: read
    uses: blck-snwmn/share-workflows/.github/workflows/reusable-eslint.yml@main
    with:
      working-directory: ./syncworker