name: lint

on:
  push:
  pull_request:

jobs:
  golint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "./client/go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --enable=gosec
          working-directory: ./client
  eslint:
    uses: blck-snwmn/share-workflows/.github/workflows/reusable-eslint.yml@main
    with:
      working-directory: ./syncworker