name: eslint

on:
  pull_request:
    paths:
      - syncworker/**
jobs:
  lint:
    permissions:
      pull-requests: write
      contents: read
    uses: blck-snwmn/share-workflows/.github/workflows/reusable-eslint.yml@main
    with:
      working-directory: ./syncworker