name: lint

on:
  push:
  pull_request:

jobs:
  golint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "./client/go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --enable=gosec
          working-directory: ./client
  eslint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write 
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          workdir: ./syncworker