name: go

on:
  push:
    paths:
      - client/**
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: blck-snwmn/share-workflows/go/lint@main
        with:
          working-directory: ./client
