name: eslint

on:
  push:
    paths:
      - syncworker/**
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: check(lint, format)
        run: npm run check
        working-directory: ./syncworker